export const PATH = 'http://192.168.2.55:8026/'; // 2018-09-11 15:35

export const ASYNC_URLS = {
  'login': PATH + 'rmApi/login/accountLogin/validateLoginPassword', // 登录验证
  'resetPassword': PATH + 'rmApi/userManage/account/resetPassword', // 重置密码
  'saveAccount': PATH + 'rmApi/userManage/account/saveAccountAllInfo', // 用户注册
  'accountList': PATH + 'rmApi/userManage/account/listAccountAllInfo', // 查询用户列表或者根据条件查询
  'rolesList': PATH + 'rmApi/userManage/role/list', // 查询角色列表或者根据条件查询
  'accountGroupsList': PATH + 'rmApi/userManage/group/list', // 查询用户组列表或者根据条件查询
  'hospitalList': PATH + 'rmApi/base/baseHospital/list', // 查询医院列表
  'hospitalById': PATH + 'rmApi/base/baseHospital/findById', // 根据ID查询医院
  'saveHosp': PATH + 'rmApi/base/baseHospital/save', // 新增医院数据
  'vendorList': PATH + 'rmApi/base/baseVendor/list', // 查询厂商列表
  'saveVendor': PATH + 'rmApi/base/baseVendor/save', // 保存厂商，保存产商和产商租户关系
  'certificateList': PATH + 'rmApi/base/baseCert/list', // 查询资质列表
  'baseVendorFindById': PATH + 'rmApi/base/baseCert/findById', // 获取资质信息
  'updateVendor': PATH + 'rmApi/base/baseVendor/update', // 更新厂商信息
  'saveVendorCert': PATH + 'rmApi/base/baseCert/save', // 上传资质信息
  'sendCode': PATH + 'rmApi/login/authenticode/getCode', // 发送验证码
  'verifyCode': PATH + 'rmApi/login/authenticode/checkCode', // 验证验证码
  'updateHosp': PATH + 'rmApi/base/baseHospital/update', // 更新医院数据
  'updateAccountAllInfo': PATH + 'rmApi/userManage/account/updateAccountAllInfo', // 更新账户信息
  'getAccountRoles': PATH + 'rmApi/userManage/account/getAccountRoles', // 获取账户角色
  'updateAccount': PATH + 'rmApi/userManage/account/update', // 单独更新账户状态
  'updateRole': PATH + 'rmApi/userManage/role/update', // 单独更新角色状态
  'updateAptitudes': PATH + 'rmApi/base/baseCert/update', // 修改
  'saveAptitudesFile': PATH + 'rmApi/base/baseCertFile/save', // 修改
  'deleteAptitudesFile': PATH + 'rmApi/base/baseCertFile/batchDelete', // 批量删除
  'updateRoleAndFuncs': PATH + 'rmApi/userManage/role/updateRoleAndFuncs', // 更新角色、角色权限关系
  'getFuncsTree': PATH + 'rmApi/userManage/func/getFuncsTree', // 获取角色全部信息
  'systemList': PATH + 'rmApi/userManage/systemVersion/list', // 获取系统信息
  'vendorFindById': PATH + 'rmApi/base/baseVendor/findById', // 查询厂商信息
  'getRoleFuncsTree': PATH + 'rmApi/userManage/role/getRoleFuncsTree', // 查询角色权限树
  'productList': PATH + 'rmApi/supp/baseProduct/list',    // 查询产品
  'baseCustomerContactList': PATH + 'rmApi/supp/baseCustomerContact/list', // 联系人列表
  'baseCustomerContactFindById': PATH + 'rmApi/supp/baseCustomerContact/findById', // 联系人详情
  'baseCustomerContactSave': PATH + 'rmApi/supp/baseCustomerContact/save', // 添加联系人
  'baseCustomerContactUpdate': PATH + 'rmApi/supp/baseCustomerContact/update', // 编辑联系人
  'baseCustomerContactDelete': PATH + 'rmApi/supp/baseCustomerContact/delete', // 删除联系人
  'baseCertFileSave': PATH + 'rmApi/admin/file/upload', // 上传资质文件
  'baseOrderInfoList': PATH + 'rmApi/supp/baseOrderInfo/list', // 查询订单列表
  'findByOrderNo': PATH + 'rmApi/supp/baseOrderInfo/findByOrderNo', // 通过订单号，查询订单
  'cstList': PATH + 'rmApi/supp/baseCst/list',         // 查询耗材
  'baseOrderDeliverList': PATH + 'rmApi/supp/baseOrderDeliver/list', // 询订单详情
  'customerList': PATH + 'rmApi/supp/baseCustomer/list', // 查询客户信息
  'customerById': PATH + 'rmApi/supp/baseCustomer/findById', // 根据ID查询客户
  'findCstById': PATH + 'rmApi/supp/baseCst/findById',          // 根据id查询耗材
  'deleteCustomer': PATH + 'rmApi/supp/baseCustomer/delete', // 删除客户
  'updateClient': PATH + 'rmApi/supp/baseCustomer/update', // 更新客户信息
  'saveClient': PATH + 'rmApi/supp/baseCustomer/save', // 新增客户信息
  'batchDelete': PATH + 'rmApi/base/baseCert/batchDelete',         // 批量删除资质、相关文件/耗材
  'baseOrderInfo': PATH + 'rmApi/supp/baseOrderInfo/findById',     //  查询订单信息、相关耗材
  'updateOrder': PATH + 'rmApi/supp/baseOrderInfo/update', // 更新订单信息
  'saveDeliverCsts': PATH + 'rmApi/supp/baseOrderInfo/saveDeliverCsts',            // 保存发货信息、发货耗材，发货耗材关联，更新订单耗材发货数量（调试）
  'findOrderDeliverById': PATH + 'rmApi/supp/baseOrderDeliver/findById',         //  查询发货信息、相关耗材
  'updateDeliverDate': PATH + 'rmApi/supp/baseOrderInfo/updateDeliverDate',  // 批量修改订单预计到货时间
  'updateOrderDeliver': PATH + 'rmApi/supp/baseOrderDeliver/update',       //  更新发货信息
  'saveConfirmCsts': PATH + 'rmApi/supp/baseOrderInfo/saveConfirmCsts', // 保存确认订单
  'baseCstSave': PATH + 'rmApi/supp/baseCst/save', // 添加产品
  'baseCstSpecSave': PATH + 'rmApi/supp/baseCstSpec/save', // 添加产品规格
  'baseCstSpecList': PATH + 'rmApi/supp/baseCstSpec/list', // 查询产品规格
  'baseCstSpecUpdate': PATH + 'rmApi/supp/baseCstSpec/update', // 修改产品规格
  'baseCstUpdate': PATH + 'rmApi/supp/baseCst/update', // 修改产品
  'downloadFile': PATH + 'rmApi/admin/file/download', // 下载文件
  'saveRoleAndFuncs': PATH + 'rmApi/userManage/role/save', // 新增角色、权限
  'saveOrderInvoice': PATH + 'rmApi/supp/baseOrderInvoice/save',      //  保存发票
  'getOrderCsts': PATH + 'rmApi/supp/baseOrderInfo/getOrderCsts',        //  查询多个订单的耗材（医院必须一致）
  'findConfirmCsts': PATH + 'rmApi/supp/baseOrderInfo/getConfirmCsts', // 查询确认订单
  'salesReturnList': PATH + 'rmApi/supp/baseOrderReturn/list', // 退货管理列表
  'updateSalesReturn': PATH + 'rmApi/supp/baseOrderReturn/update', // 更新退货信息
  'findOrderLabel': PATH + 'rmApi/supp/baseOrderLabel/findById',                 //  查询标签
  'saveLabel': PATH + 'rmApi/supp/baseOrderLabel/saveUpdate',                       //  保存标签
  'findBaseOrderLabel': PATH + 'rmApi/supp/baseOrderLabel/list',                        //  查询标签
  'findSalesReturn': PATH + 'rmApi/supp/baseOrderReturn/findById', // 查询退货信息
  'getOrderDeliver': PATH + 'rmApi/supp/baseOrderDeliver/getOrderDeliver', // 查询多个订单详情
  'baseCstSpecDelete': PATH + 'rmApi/supp/baseCstSpec/delete', // 删除耗材规格
  'deleteFile': PATH + 'rmApi/admin/file/delete', // 删除资质文件
  'cmpDictVendor': PATH + 'rmApi/dictcp/cmpDictVendor/save', // 添加厂商字典
  'getIdsByName': PATH + 'rmApi/base/baseCert/getIdsByName', // 查询授权资质
  'customerHosps': PATH + 'rmApi/base/baseHospital/getCustomerHosps', // 查询没有关联厂商的医院
  'baseOrderInvoiceList': PATH + 'rmApi/supp/baseOrderInvoice/list', // 查询发票列表
  'baseOrderInvoiceUpdate': PATH + 'rmApi/supp/baseOrderInvoice/update', // 更新发票信息
  'baseOrderInvoiceFind': PATH + 'rmApi/supp/baseOrderInvoice/findById', // 更新发票信息
  'baseOrderInvoiceSave': PATH + 'rmApi/supp/baseOrderInvoice/save', // 新增发票信息
  'baseOrderSettlementList': PATH + 'rmApi/supp/baseOrderSettlement/list', // 查询结算列表
  'baseOrderSettlementUpdate': PATH + 'rmApi/supp/baseOrderSettlement/update', // 更新结算信息
  'baseOrderSettlementFind': PATH + 'rmApi/supp/baseOrderSettlement/findById', // 查询结算详情信息
  'baseSettlementDetailList': PATH + 'rmApi/supp/baseSettlementDetail/list', // 已结算明细列表
  'baseSettlementDetailDelete': PATH + 'rmApi/supp/baseSettlementDetail/delete', // 已结算明细删除
  'getDeliverNo': PATH + 'rmApi/supp/baseOrderDeliver/getDeliverNo', // 获取发货单号
  'getSettlementCst': PATH + 'rmApi/supp/baseDeliverCst/getSettlementCst', // 未结算发货单列表
  'saveSettlementCst': PATH + 'rmApi/supp/baseDeliverCst/saveSettlementCst', // 保存未结算发货表格信息
  'getSettlementNum': PATH + 'rmApi/supp/baseDeliverCstRelate/getSettlementNum', // 查询单条发货耗材信息
  'baseDeliverCst': PATH + 'rmApi/supp/baseDeliverCst/list',       //  查询发货耗材，及其发货单编号、打印标记
  'baseDeliverCstUpdate': PATH + 'rmApi/supp/baseDeliverCst/update',        // 更新发货耗材标签
  'baseTransMsgList': PATH + 'rmApi/admin/baseTransMsg/list',          //  查询消息，条件查询
  'baseTransMsgUpdate': PATH + 'rmApi/admin/baseTransMsg/update',             //  更新消息，只更新传入数据
  'cstSpecInfoList': PATH + 'rmApi/supp/cstSpecInfo/list', // 查询耗材规格，以规格组织数据
  'baseCstPriceList': PATH + 'rmApi/supp/baseCstPrice/list', // 查询耗材价格
  'baseCstPriceUpdate': PATH + 'rmApi/supp/baseCstPrice/update', // 更新耗材价格
  'findMessage': PATH + 'rmApi/admin/baseTransMsg/list', // 查询通知信息
  'gatherInfo': PATH + 'rmApi/admin/cmpIndex/find', // 汇总信息
  'baseCstPriceSave': PATH + 'rmApi/supp/baseCstPrice/save', // 保存耗材价格
  'baseCstPriceDelete': PATH + 'rmApi/supp/baseCstPrice/delete', // 删除价格
  'baseOrderLogList': PATH + 'rmApi/supp/baseOrderLog/list', // 查询订单日志
  'getOrderMergeCsts': PATH + 'rmApi/supp/baseOrderInfo/getOrderMergeCsts',   //  查询多个订单的耗材（相同耗材合并成一个）
};

export const DICT_URLS = {
  'dictFind': PATH + 'rmApi/dictcp/baseDict/find', // 缓存字典
  'country': PATH + 'rmApi/dictcp/baseDictCountry/list', // 国家列表
  'province': PATH + 'rmApi/dictcp/baseDictProvince/list', // 省份列表
  'city': PATH + 'rmApi/dictcp/baseDictCity/list', // 市级列表
  'county': PATH + 'rmApi/dictcp/baseDictCounty/list', // 区县列表
  'cstTypeDict': PATH + 'rmApi/dictcp/cmpDictCstType/list', // 产品分类字典
  'authorVendor': PATH + 'rmApi/dictcp/cmpDictVendor/list' // 授权厂商
};

